In [1]:
from openmmtools.testsystems import WaterBox
import calibrate
from simtk import openmm, unit
from simtk.openmm import app
import numpy as np

# SAMS class tester
Seeing if the self ajdustem mixture sampling class `SaltSAMS` actually works!

Creating a box of water:

In [2]:
size = 20.0*unit.angstrom     # The length of the edges of the water box.
temperature = 300*unit.kelvin
pressure = 1*unit.atmospheres
delta_chem = 0*unit.kilojoule_per_mole

# Creating the test system
wbox = WaterBox(box_edge=size,nonbondedMethod=app.PME)

Generating the SAMS sampler object:

In [3]:
state = calibrate.SaltSAMS(wbox.system,wbox.topology,wbox.positions,temperature,pressure,
                           mdsteps=10,saltsteps=1,niterations=600,burnin=100,b=0.9,saltmax=5)

In [6]:
state.zeta = np.arange(5+1)*282

In [7]:
state.calibration()

In [8]:
state.zeta

array([   0,  275,  557,  839, 1121, 1403])

In [20]:
state.statetime

[0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,


In [21]:
state.zeta

array([  0.        ,   2.20246355,   2.78038528,  -2.93443164,
        -3.20406166,  18.98905384])

In [25]:
np.savetxt(fname='zeta.txt',X=state.zeta,newline='')

In [8]:
f = open('currentstate.txt', 'a')
s = '{:9} {:3}\n'.format(i,state.nsalt.T)
f.close()

1000.0

In [29]:
' '.join(map(str,state.zeta))+'\n'

'0.0 2.20246354937 2.78038528474 -2.93443164445 -3.20406165831 18.9890538445\n'

In [12]:
niterations = 1000000
blocklength = 100

In [13]:
nblocks = niterations/blocklength

In [14]:
nblocks

10000

In [17]:
20021 % 100

21

In [18]:
nblocks*blocklength

1000000

In [31]:
10 % 3

1

In [32]:
167/0.592

282.0945945945946

In [34]:
np.arange(6)*282

array([   0,  282,  564,  846, 1128, 1410])